# Generated by Django 2.2.3 on 2019-10-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('preis', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('datum', models.DateField(blank=True, default=None, null=True)),
                ('cover', models.ImageField(blank=True, upload_to='covers/')),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
