# Generated by Django 2.2.3 on 2019-10-13 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBooks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Buch',
        ),
    ]
