# Generated by Django 2.2.3 on 2019-10-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBooks', '0002_auto_20191013_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='buch',
            name='autor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='buch',
            name='status',
            field=models.CharField(choices=[('0', 'verfügbar'), ('1', 'ausgeliehen'), ('2', 'nicht verfügbar'), ('3', 'nicht existiert')], default='', max_length=30, null=True, unique=True),
        ),
    ]
