# Generated by Django 2.2.3 on 2019-10-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBooks', '0003_auto_20191013_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buch',
            name='status',
            field=models.CharField(choices=[('nicht verfügbar', 'nicht verfügbar'), ('ausgeliehen', 'ausgeliehen'), ('nicht existiert', 'nicht existiert'), ('verfügbar', 'verfügbar')], default='', max_length=30, null=True, unique=True),
        ),
    ]
