# Generated by Django 2.2.3 on 2019-10-13 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myBooks', '0004_auto_20191013_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buchnumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbin_1', models.CharField(blank=True, max_length=10)),
                ('isbin_2', models.CharField(blank=True, max_length=13)),
            ],
        ),
        migrations.AlterField(
            model_name='buch',
            name='status',
            field=models.CharField(choices=[('verfügbar', 'verfügbar'), ('ausgeliehen', 'ausgeliehen'), ('nicht existiert', 'nicht existiert'), ('nicht verfügbar', 'nicht verfügbar')], default='', max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='buch',
            name='number',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myBooks.Buchnumber'),
        ),
    ]
