# Generated by Django 2.2.3 on 2019-10-13 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myBooks', '0005_auto_20191013_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buch',
            name='status',
            field=models.CharField(choices=[('nicht existiert', 'nicht existiert'), ('ausgeliehen', 'ausgeliehen'), ('nicht verfügbar', 'nicht verfügbar'), ('verfügbar', 'verfügbar')], default='', max_length=30, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myBooks.Buch')),
            ],
        ),
    ]
