# Generated by Django 2.2.3 on 2019-10-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBooks', '0008_auto_20191013_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buch',
            name='status',
            field=models.CharField(choices=[('ausgeliehen', 'ausgeliehen'), ('verfügbar', 'verfügbar'), ('nicht existiert', 'nicht existiert'), ('nicht verfügbar', 'nicht verfügbar')], default='', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('viertes Semester', 'viertes Semester'), ('drittes Semester', 'drittes Semester'), ('fünftes Semester', 'fünftes Semester'), ('erstes Semester', 'erstes Semester'), ('zweites Semester', 'zweites Semester'), ('sechstes Semester', 'sechstes Semester')], default='', max_length=50, null=True, unique=True),
        ),
    ]
