# Generated by Django 2.2.3 on 2019-10-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBooks', '0009_auto_20191013_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='martikelnummer',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buch',
            name='status',
            field=models.CharField(choices=[('ausgeliehen', 'ausgeliehen'), ('nicht existiert', 'nicht existiert'), ('verfügbar', 'verfügbar'), ('nicht verfügbar', 'nicht verfügbar')], default='', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('sechstes Semester', 'sechstes Semester'), ('fünftes Semester', 'fünftes Semester'), ('zweites Semester', 'zweites Semester'), ('drittes Semester', 'drittes Semester'), ('erstes Semester', 'erstes Semester'), ('viertes Semester', 'viertes Semester')], default='', max_length=50, null=True, unique=True),
        ),
    ]
