# Generated by Django 2.2.3 on 2019-10-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBooks', '0010_auto_20191013_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buch',
            name='status',
            field=models.CharField(choices=[('nicht verfügbar', 'nicht verfügbar'), ('ausgeliehen', 'ausgeliehen'), ('verfügbar', 'verfügbar'), ('nicht existiert', 'nicht existiert')], default='', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='martikelnummer',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('viertes Semester', 'viertes Semester'), ('erstes Semester', 'erstes Semester'), ('drittes Semester', 'drittes Semester'), ('sechstes Semester', 'sechstes Semester'), ('zweites Semester', 'zweites Semester'), ('fünftes Semester', 'fünftes Semester')], default='', max_length=50, null=True, unique=True),
        ),
    ]
