# Generated by Django 2.2.3 on 2019-10-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBooks', '0011_auto_20191013_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buch',
            name='status',
            field=models.CharField(choices=[('nicht existiert', 'nicht existiert'), ('verfügbar', 'verfügbar'), ('ausgeliehen', 'ausgeliehen'), ('nicht verfügbar', 'nicht verfügbar')], default='', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('fünftes Semester', 'fünftes Semester'), ('viertes Semester', 'viertes Semester'), ('zweites Semester', 'zweites Semester'), ('sechstes Semester', 'sechstes Semester'), ('drittes Semester', 'drittes Semester'), ('erstes Semester', 'erstes Semester')], default='', max_length=50, null=True, unique=True),
        ),
    ]
