# Generated by Django 2.2.3 on 2019-10-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBooks', '0012_auto_20191013_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buch',
            name='status',
            field=models.CharField(choices=[('nicht verfügbar', 'nicht verfügbar'), ('ausgeliehen', 'ausgeliehen'), ('verfügbar', 'verfügbar'), ('nicht existiert', 'nicht existiert')], default='', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('drittes Semester', 'drittes Semester'), ('zweites Semester', 'zweites Semester'), ('erstes Semester', 'erstes Semester'), ('sechstes Semester', 'sechstes Semester'), ('viertes Semester', 'viertes Semester'), ('fünftes Semester', 'fünftes Semester')], default='', max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('books', models.ManyToManyField(to='myBooks.Buch')),
            ],
        ),
    ]
