# Generated by Django 2.2.3 on 2019-10-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBooks', '0013_auto_20191016_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='surname',
        ),
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='myBooks.Buch'),
        ),
        migrations.AlterField(
            model_name='buch',
            name='status',
            field=models.CharField(choices=[('verfügbar', 'verfügbar'), ('ausgeliehen', 'ausgeliehen'), ('nicht verfügbar', 'nicht verfügbar'), ('nicht existiert', 'nicht existiert')], default='', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('sechstes Semester', 'sechstes Semester'), ('fünftes Semester', 'fünftes Semester'), ('drittes Semester', 'drittes Semester'), ('erstes Semester', 'erstes Semester'), ('zweites Semester', 'zweites Semester'), ('viertes Semester', 'viertes Semester')], default='', max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=40)),
                ('prof', models.CharField(max_length=30)),
                ('studenten', models.ManyToManyField(related_name='studenten', to='myBooks.Student')),
            ],
        ),
    ]
