# Generated by Django 2.2.3 on 2019-10-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBooks', '0014_auto_20191017_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modul',
            name='studenten',
        ),
        migrations.AddField(
            model_name='modul',
            name='modulnummer',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='moduls',
            field=models.ManyToManyField(to='myBooks.Modul'),
        ),
        migrations.AlterField(
            model_name='buch',
            name='status',
            field=models.CharField(choices=[('nicht existiert', 'nicht existiert'), ('verfügbar', 'verfügbar'), ('ausgeliehen', 'ausgeliehen'), ('nicht verfügbar', 'nicht verfügbar')], default='', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('fünftes Semester', 'fünftes Semester'), ('zweites Semester', 'zweites Semester'), ('viertes Semester', 'viertes Semester'), ('drittes Semester', 'drittes Semester'), ('erstes Semester', 'erstes Semester'), ('sechstes Semester', 'sechstes Semester')], default='', max_length=50, null=True, unique=True),
        ),
    ]
