# Generated by Django 2.2.3 on 2019-10-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBooks', '0016_auto_20191019_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='moduls',
        ),
        migrations.AddField(
            model_name='student',
            name='modul_name',
            field=models.ManyToManyField(related_name='moduls', to='myBooks.Modul'),
        ),
        migrations.AlterField(
            model_name='buch',
            name='status',
            field=models.CharField(choices=[('nicht existiert', 'nicht existiert'), ('nicht verfügbar', 'nicht verfügbar'), ('verfügbar', 'verfügbar'), ('ausgeliehen', 'ausgeliehen')], default='', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('viertes Semester', 'viertes Semester'), ('fünftes Semester', 'fünftes Semester'), ('zweites Semester', 'zweites Semester'), ('drittes Semester', 'drittes Semester'), ('erstes Semester', 'erstes Semester'), ('sechstes Semester', 'sechstes Semester')], default='', max_length=50, null=True, unique=True),
        ),
    ]
