# Generated by Django 2.2.3 on 2019-10-19 12:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myBooks', '0017_auto_20191019_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='buch',
            name='status',
            field=models.CharField(choices=[('nicht verfügbar', 'nicht verfügbar'), ('ausgeliehen', 'ausgeliehen'), ('verfügbar', 'verfügbar'), ('nicht existiert', 'nicht existiert')], default='', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='modul_name',
            field=models.ManyToManyField(related_name='studetenmodule', to='myBooks.Modul'),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('viertes Semester', 'viertes Semester'), ('sechstes Semester', 'sechstes Semester'), ('drittes Semester', 'drittes Semester'), ('erstes Semester', 'erstes Semester'), ('zweites Semester', 'zweites Semester'), ('fünftes Semester', 'fünftes Semester')], default='', max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myBooks.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'movie')},
                'index_together': {('user', 'movie')},
            },
        ),
    ]
