# Generated by Django 2.2.3 on 2019-10-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBooks', '0018_auto_20191019_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buch',
            name='status',
            field=models.CharField(choices=[('nicht existiert', 'nicht existiert'), ('ausgeliehen', 'ausgeliehen'), ('nicht verfügbar', 'nicht verfügbar'), ('verfügbar', 'verfügbar')], default='', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('drittes Semester', 'drittes Semester'), ('zweites Semester', 'zweites Semester'), ('viertes Semester', 'viertes Semester'), ('erstes Semester', 'erstes Semester'), ('sechstes Semester', 'sechstes Semester'), ('fünftes Semester', 'fünftes Semester')], default='', max_length=50, null=True, unique=True),
        ),
    ]
