# Generated by Django 2.2.3 on 2019-10-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBooks', '0019_auto_20191019_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buch',
            name='status',
            field=models.CharField(choices=[('nicht existiert', 'nicht existiert'), ('nicht verfügbar', 'nicht verfügbar'), ('verfügbar', 'verfügbar'), ('ausgeliehen', 'ausgeliehen')], default='', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('zweites Semester', 'zweites Semester'), ('drittes Semester', 'drittes Semester'), ('sechstes Semester', 'sechstes Semester'), ('fünftes Semester', 'fünftes Semester'), ('viertes Semester', 'viertes Semester'), ('erstes Semester', 'erstes Semester')], default='', max_length=50, null=True, unique=True),
        ),
    ]
